services:
  app:
    image: ghcr.io/rcroger/spliit/spliit:main
    ports:
      - 3000:3001
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
